#cloud-config

---

# include one or more SSH public keys
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy8xNHI82UuCSWa72GcoSXjYWoDk2B3rA7bVPzx87/i3VodRGh4EAd2gs6w2Mts3AgFtlXrRvcPQEQyE4HOCibrHQOh1IucXh+iMs8KQFXJ8yPYs0QJUZRdrM+cOfyIyOhaiSjZCgACKW851HUzCUZt9KXWlWnNUcpnbFY43uhxJ7Q1urM/Qp8gO9clhFd7UDJCHSQXiImrIGCtuh7IENLWqrlH+Fgafb+3S6u/5CYU8+XtV9SD4fzHOn7vXSMk5nSCpFKIhscGMj1zHquZcKqv38cO8ZbmVn5LUMsDkSEXg2XET4ZH03Zl6TR3wpIexHtIzjxctLvKVG6jvwaz303 toby@Tobys-MacBook-Pro.local

# hostname: "coreos1"


coreos:
  fleet:
    public-ip: $public_ipv4
  flannel:
    interface: $public_ipv4
  update:
    reboot-strategy: reboot
  units:
  - name: etcd-env-generator.service
    command: start
    content: |
      [Unit]
      Description=Creates an EnvironmentFile with etcd2 setup on private network to be injected into etcd2 service
      Documentation=https://github.com/pavlo/coreos-utils/etcd-env-generator
      Requires=network.target
      After=network.target
      [Service]
      ExecStartPre=-/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/wget -N -P /opt/bin https://raw.githubusercontent.com/pavlo/coreos-utils/master/etcd-env-generator/etcd-env-generator.sh
      ExecStartPre=/usr/bin/chmod +x /opt/bin/etcd-env-generator.sh
      ExecStart=/opt/bin/etcd-env-generator.sh eth0 12187f08efc7a1f983f9143e66e124d1
      RemainAfterExit=yes
      Type=oneshot
  - name: etcd2.service
    drop-ins:
    - name: "urls.conf"
      content: |
        [Unit]
        Requires=etcd-env-generator.service
        After=etcd-env-generator.service
        [Service]
        EnvironmentFile=/etc/etcd2-environment
  - name: fleet.service
    command: start
  - name: format-ephemeral.service
    command: start
    content: |
      [Unit]
      Description=Formats the ephemeral drive
      After=dev-xvdb.device
      Requires=dev-xvdb.device
      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/sbin/wipefs -f /dev/xvdb
      ExecStart=/usr/sbin/mkfs.ext4 -F /dev/xvdb
  - name: var-lib-docker.mount
    command: start
    content: |
      [Unit]
      Description=Mount ephemeral to /var/lib/docker
      Requires=format-ephemeral.service
      After=format-ephemeral.service
      [Mount]
      What=/dev/xvdb
      Where=/var/lib/docker
      Type=ext4
  - name: docker.service
    drop-ins:
      - name: 10-wait-docker.conf
        content: |
          [Unit]
          After=var-lib-docker.mount
          Requires=var-lib-docker.mount
